import the library and load the file

In [1]:
import pandas as pd
df = pd.read_csv(r'C:\Users\ADMIN\OneDrive\Desktop\5thsem_OJT\project1_diabetes\data\raw\project1_diabetes_raw.csv')

Conform the load succeeded

In [2]:
len(df)

968

Load only the first five rows

In [3]:
df_100 = pd.read_csv(r'C:\Users\ADMIN\OneDrive\Desktop\5thsem_OJT\project1_diabetes\data\raw\project1_diabetes_raw.csv',nrows=100)

In [4]:
len(df_100)

100

Record the dataset dimension

In [5]:
df.shape

(968, 14)

In [6]:
df.shape[0]

968

In [7]:
df.shape[1]

14

List every columns name

In [8]:
df.columns.tolist()

['patient_id',
 'age',
 'gender',
 'pregnancies',
 'glucose',
 'blood_pressure',
 'skin_thickness',
 'insulin',
 'bmi',
 'diabetes_pedigree',
 'physical_activity',
 'smoker',
 'last_checkup_date',
 'outcome']

In [9]:
df.dtypes

patient_id               str
age                  float64
gender                   str
pregnancies            int64
glucose                int64
blood_pressure         int64
skin_thickness         int64
insulin                int64
bmi                  float64
diabetes_pedigree    float64
physical_activity        str
smoker                   str
last_checkup_date        str
outcome                int64
dtype: object

Look at the top of the file

In [10]:
df.head(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79.0,male,0,124,71,30,0,23.4,0.588,NaN,No,20/04/2023,0
1,P00108,37.0,Male,0,153,85,24,42,33.9,0.192,medium,Y,03/05/2024,1
2,P00517,39.0,F,0,142,68,22,159,26.9,0.777,low,NaN,08/07/2023,0
3,P00687,68.0,female,7,121,88,0,0,29.0,1.217,NaN,Y,14/04/2024,1
4,P00927,75.0,female,0,107,84,31,101,21.2,0.278,Low,No,27/01/2024,0
5,P00755,37.0,female,0,145,80,0,0,22.0,0.488,HIGH,Yes,10/01/2024,0
6,P00431,58.0,Male,5,95,72,0,170,27.2,0.197,HIGH,N,25/12/2023,0
7,P00542,58.0,Female,3,150,68,17,0,46.0,0.808,Medium,No,20/06/2024,1
8,P00929,32.0,Female,6,129,74,0,226,20.6,0.655,High,NaN,15/10/2023,1
9,P00513,61.0,Female,0,161,77,35,201,35.0,1.229,Medium,Y,22/12/2023,1

Look at the bottom of the file

In [11]:
df.tail(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
958,P00584,47.0,Female,0,107,59,26,98,32.7,0.050,HIGH,No,20/07/2023,0
959,P00674,42.0,Female,5,124,71,22,121,NaN,0.400,NaN,N,01/06/2024,0
960,P00333,59.0,Male,0,141,67,44,305,28.8,0.705,Low,NaN,27/03/2023,1
961,P00270,36.0,Male,0,99,52,13,10,20.8,0.432,medium,Y,12/05/2024,0
962,P00501,39.0,Male,0,92,62,45,16,34.5,0.143,Medium,Yes,01/10/2023,0
963,P00338,64.0,male,2,0,81,34,0,40.3,0.641,Medium,Yes,17/11/2023,0
964,P00092,71.0,F,0,140,64,37,0,33.4,0.116,Low,Y,20/05/2023,1
965,P00081,40.0,Female,0,130,73,0,258,20.1,0.709,Low,N,07/06/2023,0
966,P00704,52.0,F,4,123,76,22,189,38.9,0.540,High,N,05/06/2024,0
967,P00922,42.0,Male,0,114,73,34,0,28.2,0.819,medium,N,10/10/2023,0

Take a reproducible random sample

In [12]:
df.sample(10, random_state=7)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
684,P00739,23.0,female,0,131,66,0,68,23.4,0.653,low,No,03/07/2024,0
564,P00518,74.0,Female,0,104,76,21,0,39.8,0.926,low,Yes,14/07/2024,0
384,P00688,26.0,Male,0,124,74,22,197,30.7,0.612,medium,N,08/06/2023,0
24,P00836,66.0,M,5,115,70,21,42,18.9,0.403,Medium,N,28/07/2023,0
299,P00121,51.0,Female,6,122,77,32,188,35.9,0.184,NaN,N,15/01/2023,0
171,P00203,53.0,Male,0,82,80,42,146,34.1,0.881,Medium,Yes,15/12/2023,0
839,P00844,79.0,F,2,107,62,16,62,34.8,0.050,HIGH,NaN,23/07/2023,0
568,P00009,76.0,Female,0,132,65,0,0,NaN,0.541,High,N,11/01/2024,0
351,P00823,39.0,Female,7,94,90,0,0,NaN,0.541,low,N,14/07/2023,0
168,P00180,38.0,Female,0,75,56,0,86,29.8,0.473,low,N,22/07/2024,0

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 968 entries, 0 to 967
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   patient_id         968 non-null    str
 1   age                959 non-null    float64
 2   gender             968 non-null    str
 3   pregnancies        968 non-null    int64
 4   glucose            968 non-null    int64
 5   blood_pressure     968 non-null    int64
 6   skin_thickness     968 non-null    int64
 7   insulin            968 non-null    int64
 8   bmi                930 non-null    float64
 9   diabetes_pedigree  968 non-null    float64
 10  physical_activity  910 non-null    str
 11  smoker             921 non-null    str
 12  last_checkup_date  968 non-null    str
 13  outcome            968 non-null    int64
dtypes: float64(3), int64(6), str(5)
memory usage: 106.0 KB

Summarise every numeric columns

In [14]:
df.describe()

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,outcome
count,959.000000,968.000000,968.000000,968.000000,968.000000,968.000000,930.000000,968.000000,968.000000
mean,49.883212,1.841942,114.324380,68.558884,20.596074,97.250000,30.796452,0.461834,0.286157
std,17.581570,2.616236,34.571781,19.449206,14.174823,118.072391,9.346399,0.285026,0.452197
min,21.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050000,0.000000
25%,35.000000,0.000000,95.000000,63.000000,8.000000,0.000000,26.200000,0.243500,0.000000
50%,50.000000,0.000000,116.000000,71.000000,22.000000,83.000000,30.900000,0.445500,0.000000
75%,65.000000,4.000000,136.000000,79.000000,31.000000,161.000000,35.675000,0.654250,1.000000
max,81.000000,8.000000,215.000000,107.000000,67.000000,1399.000000,94.500000,1.532000,1.000000

In [15]:
df.describe(include="all")

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
count,968,959.000000,968,968.000000,968.000000,968.000000,968.000000,968.000000,930.000000,968.000000,910,921,968,968.000000
unique,950,NaN,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,4,499,NaN
top,P00826,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,medium,N,11/01/2024,NaN
freq,2,NaN,223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159,380,8,NaN
mean,NaN,49.883212,NaN,1.841942,114.324380,68.558884,20.596074,97.250000,30.796452,0.461834,NaN,NaN,NaN,0.286157
std,NaN,17.581570,NaN,2.616236,34.571781,19.449206,14.174823,118.072391,9.346399,0.285026,NaN,NaN,NaN,0.452197
min,NaN,21.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050000,NaN,NaN,NaN,0.000000
25%,NaN,35.000000,NaN,0.000000,95.000000,63.000000,8.000000,0.000000,26.200000,0.243500,NaN,NaN,NaN,0.000000
50%,NaN,50.000000,NaN,0.000000,116.000000,71.000000,22.000000,83.000000,30.900000,0.445500,NaN,NaN,NaN,0.000000
75%,NaN,65.000000,NaN,4.000000,136.000000,79.000000,31.000000,161.000000,35.675000,0.654250,NaN,NaN,NaN,1.000000
max,NaN,81.000000,NaN,8.000000,215.000000,107.000000,67.000000,1399.000000,94.500000,1.532000,NaN,NaN,NaN,1.000000

In [16]:
df["gender"].nunique()

12

In [17]:
df["gender"].unique()

<StringArray>
[   'male',    'Male',       'F',  'female',  'Female',       'M', 'female ',
      'M ',   'Male ', 'Female ',   'male ',      'F ']
Length: 12, dtype: str

Count occurrences include missing value

In [18]:
df["gender"].value_counts(dropna=False)

gender
Female     223
Male       207
female     207
F          120
male       118
M           53
Male        12
Female       7
male         7
F            7
female       4
M            3
Name: count, dtype: int64

In [19]:
df['outcome'].value_counts()

outcome
0    691
1    277
Name: count, dtype: int64

In [20]:
df['outcome'].value_counts(normalize=True)

outcome
0    0.713843
1    0.286157
Name: proportion, dtype: float64

compare group sizes

In [22]:
df.groupby('outcome').size()

outcome
0    691
1    277
dtype: int64

compare average measurements across the two groups

In [23]:
df.groupby('outcome').mean(numeric_only=True)

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree
outcome,,,,,,,,
0,47.922287,1.816208,108.596237,68.555716,20.824891,97.204052,30.303916,0.441114
1,54.711191,1.906137,128.613718,68.566787,20.025271,97.364621,32.025940,0.513520

In [24]:
df.groupby('outcome')[['glucose','age']].mean()

            glucose        age
outcome
0        108.596237  47.922287
1        128.613718  54.711191

rank features by difference

In [25]:
#glucose#
#bmi#
#age#
#pregnencies#
#diabetes_pedigree#

compare more than mean

In [26]:
df.groupby('outcome')[['glucose','age']].agg(['mean','median','std'])

            glucose                          age
               mean median        std       mean median        std
outcome
0        108.596237  111.0  32.946869  47.922287   47.0  17.243479
1        128.613718  130.0  34.449168  54.711191   57.0  17.503922

In [27]:
import matplotlib.pyplot as plt

## DATA CLEANING

Count missing values per column

In [31]:
df.isnull().sum()

patient_id            0
age                   9
gender                0
pregnancies           0
glucose               0
blood_pressure        0
skin_thickness        0
insulin               0
bmi                  38
diabetes_pedigree     0
physical_activity    58
smoker               47
last_checkup_date     0
outcome               0
dtype: int64

In [32]:
df.isnull().sum().sum()

np.int64(152)

In [33]:
df.isnull().mean()

patient_id           0.000000
age                  0.009298
gender               0.000000
pregnancies          0.000000
glucose              0.000000
blood_pressure       0.000000
skin_thickness       0.000000
insulin              0.000000
bmi                  0.039256
diabetes_pedigree    0.000000
physical_activity    0.059917
smoker               0.048554
last_checkup_date    0.000000
outcome              0.000000
dtype: float64

inspect the affected rows

In [ ]:
df[df['physical_activity'].isnull(          )]

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79.0,male,0,124,71,30,0,23.4,0.588,NaN,No,20/04/2023,0
3,P00687,68.0,female,7,121,88,0,0,29.0,1.217,NaN,Y,14/04/2024,1
14,P00462,31.0,female,0,100,0,35,121,27.2,0.498,NaN,NaN,14/01/2023,0
26,P00801,69.0,female,6,116,71,0,52,20.6,0.465,NaN,N,26/04/2024,0
31,P00057,24.0,female,0,117,83,20,230,27.5,0.779,NaN,N,21/06/2024,0
63,P00144,21.0,M,4,107,70,41,178,45.1,0.092,NaN,N,17/06/2024,0
66,P00524,64.0,Male,0,172,68,52,109,93.1,0.311,NaN,Y,01/11/2023,1
100,P00184,29.0,Female,2,145,0,26,142,NaN,0.330,NaN,N,18/12/2024,0
138,P00895,63.0,Female,0,122,83,0,65,30.5,0.677,NaN,N,15/02/2024,1
145,P00795,80.0,Male,5,120,66,0,0,26.2,0.060,NaN,Yes,07/04/2023,1
149,P00802,33.0,female,0,108,52,0,162,40.7,0.628,NaN,N,19/02/2024,0
163,P00373,26.0,M,0,105,74,34,134,36.7,0.651,NaN,Y,16/05/2024,0
236,P00218,36.0,Female,0,94,59,0,159,27.6,0.723,NaN,Y,23/09/2024,0
241,P00193,21.0,Male,0,138,73,41,180,32.8,0.050,NaN,No,18/10/2024,0
299,P00121,51.0,Female,6,122,77,32,188,35.9,0.184,NaN,N,15/01/2023,0
302,P00295,61.0,Female,2,113,68,22,0,44.2,0.444,NaN,No,18/03/2023,0
308,P00118,33.0,F,0,107,79,29,66,33.8,0.238,NaN,N,17/08/2023,0
349,P00156,48.0,Female,0,59,0,10,164,31.8,0.360,NaN,No,26/08/2024,0
360,P00021,48.0,Female,0,112,75,27,0,NaN,0.435,NaN,N,01/05/2023,1
374,P00366,71.0,Male,2,155,81,22,56,39.5,0.924,NaN,N,17/01/2023,0
391,P00182,34.0,Male,0,121,76,25,73,23.6,0.568,NaN,N,24/07/2023,0
431,P00923,NaN,female,0,160,91,5,0,41.4,0.139,NaN,No,24/05/2023,0
435,P00702,35.0,Male,4,118,82,0,32,40.1,0.316,NaN,N,13/01/2024,0
450,P00054,70.0,F,7,115,66,25,139,26.6,0.452,NaN,Yes,08/12/2023,0
457,P00883,33.0,female,1,169,51,32,126,80.9,0.472,NaN,Yes,07/12/2024,0
467,P00175,60.0,Male,0,150,64,0,0,37.6,0.866,NaN,N,06/05/2023,1
497,P00286,30.0,female,5,94,67,28,226,36.4,0.349,NaN,Yes,16/03/2023,0
521,P00114,41.0,Male,0,124,68,43,181,NaN,0.093,NaN,Y,06/04/2023,0
612,P00112,55.0,female,0,82,84,9,0,23.8,0.355,NaN,Y,02/06/2023,0
616,P00500,36.0,Female,0,108,0,7,197,27.5,0.351,NaN,N,15/11/2023,0
620,P00407,61.0,female,7,97,59,41,175,29.4,0.401,NaN,N,14/04/2024,0
627,P00415,66.0,F,0,132,76,20,142,28.4,0.399,NaN,NaN,27/08/2023,1
677,P00528,63.0,Male,8,96,85,13,0,41.9,0.334,NaN,Y,05/08/2024,0
681,P00913,21.0,Male,0,110,63,20,0,43.0,0.384,NaN,N,09/03/2023,0
696,P00031,33.0,F,0,104,68,23,0,30.7,0.517,NaN,Yes,15/11/2023,0
708,P00676,32.0,M,0,93,68,21,259,32.0,0.494,NaN,Y,27/01/2024,0
716,P00194,80.0,female,2,93,64,27,113,43.0,0.224,NaN,No,01/08/2023,0
728,P00794,28.0,female,0,136,67,0,10,32.3,0.564,NaN,Yes,14/05/2024,0
757,P00346,71.0,Female,0,126,71,25,143,30.7,0.521,NaN,N,25/10/2023,0
773,P00735,24.0,female,3,115,79,18,0,15.0,0.253,NaN,No,01/10/2023,0
801,P00826,79.0,male,0,124,71,30,0,23.4,0.588,NaN,No,20/04/2023,0
820,P00216,76.0,female,0,129,78,0,11,35.2,0.095,NaN,No,26/08/2024,0
831,P00806,67.0,male,8,84,61,34,906,41.4,0.087,NaN,NaN,08/07/2023,0
833,P00101,32.0,Female,0,157,73,20,187,27.7,0.866,NaN,N,06/04/2023,1
835,P00578,41.0,Female,4,117,60,12,180,38.6,0.977,NaN,No,15/12/2024,0
852,P00186,54.0,female,0,140,0,19,263,NaN,0.832,NaN,No,01/02/2024,0
857,P00800,63.0,Female,1,127,68,0,139,0.0,0.281,NaN,No,24/09/2024,0
858,P00120,51.0,F,0,123,67,26,110,28.0,0.175,NaN,No,05/02/2023,0
859,P00947,67.0,Female,2,143,71,33,203,43.9,0.050,NaN,N,20/02/2023,0
865,P00819,27.0,Female,1,99,0,39,117,22.1,0.649,NaN,No,08/05/2023,0
872,P00381,66.0,female,0,135,86,27,0,21.0,0.818,NaN,No,24/06/2023,1
884,P00019,37.0,F,1,93,82,43,113,39.8,0.329,NaN,Y,23/11/2023,0
900,P00700,64.0,Male,0,190,70,33,115,26.8,0.279,NaN,Y,26/07/2024,0
909,P00497,26.0,female,5,93,45,14,84,27.8,0.050,NaN,NaN,27/03/2023,0
911,P00336,44.0,male,0,0,87,39,0,31.9,0.050,NaN,N,05/12/2023,0
938,P00082,35.0,Female,0,71,93,29,257,17.8,0.985,NaN,N,11/12/2024,0
955,P00622,48.0,female,7,140,82,34,162,27.5,0.885,NaN,Yes,27/07/2023,0
959,P00674,42.0,Female,5,124,71,22,121,NaN,0.400,NaN,N,01/06/2024,0

In [35]:
df[df.isnull().any(axis=1)]

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79.0,male,0,124,71,30,0,23.4,0.588,NaN,No,20/04/2023,0
2,P00517,39.0,F,0,142,68,22,159,26.9,0.777,low,NaN,08/07/2023,0
3,P00687,68.0,female,7,121,88,0,0,29.0,1.217,NaN,Y,14/04/2024,1
8,P00929,32.0,Female,6,129,74,0,226,20.6,0.655,High,NaN,15/10/2023,1
10,P00300,61.0,female,0,90,70,14,10,NaN,0.050,low,N,19/02/2023,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,P00505,24.0,Male,0,83,67,22,98,NaN,0.726,medium,N,28/02/2024,0
938,P00082,35.0,Female,0,71,93,29,257,17.8,0.985,NaN,N,11/12/2024,0
955,P00622,48.0,female,7,140,82,34,162,27.5,0.885,NaN,Yes,27/07/2023,0
959,P00674,42.0,Female,5,124,71,22,121,NaN,0.400,NaN,N,01/06/2024,0
960,P00333,59.0,Male,0,141,67,44,305,28.8,0.705,Low,NaN,27/03/2023,1

Count the placeholders

In [40]:
(df['glucose']==0).sum()

np.int64(29)